---

- name: "Find unpartitioned swap disk (6GB or 12GB)"
  set_fact:
    swap_disk: "/dev/{{ item.key }}"
    swap_part: "/dev/{{ item.key }}1"
  loop: "{{ ansible_devices | dict2items }}"
  when:
    - swap_disk is not defined             # Stop looking once we find the first match
    - item.value.partitions | length == 0  # Must be unpartitioned
    - item.value.size in ['12.00 GB', '6.00 GB']

- name: "Partition swap disk"
  community.general.parted:
    device: "{{ swap_disk }}"
    number: 1
    label: gpt
    state: present
    flags: [ swap ]
  when: swap_disk is defined

- name: "Format swap partition"
  community.general.filesystem:
    fstype: swap
    dev: "{{ swap_part }}"
  when: swap_disk is defined

- name: "Get swap partition UUID"
  ansible.builtin.command: blkid -s UUID -o value {{ swap_part }}
  register: swap_uuid
  changed_when: false
  when: swap_disk is defined

- name: "Mount and write swap entry to fstab"
  ansible.posix.mount:
    name: none
    # Mount firmly by UUID, immune to sdX/vdX enumeration shifts
    src: "UUID={{ swap_uuid.stdout }}"
    fstype: swap
    opts: defaults
    passno: '0'
    dump: '0'
    state: mounted 
  when: swap_disk is defined